# Generated by Django 6.1.1 on 2026-09-16 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('contents', models.JSONField(blank=True, default=dict, verbose_name='содержимое')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Пример: {"lesson_duration": 45, "difficulty": "medium", "questions": 10}', verbose_name='параметры генерации')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован в библиотеке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='subjects.grade', verbose_name='класс')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='subjects.materialtype', verbose_name='тип материала')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='subjects.subject', verbose_name='предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['-updated_at'],
            },
        ),
    ]
