# Generated by Django 6.1.1 on 2026-09-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='номер класса')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='название')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'классы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('system_prompt', models.TextField(blank=True, help_text='Задаётся методисту. Пример: «Ты образовательный методист. Не изменяй класс и дисциплину.»', verbose_name='системный промпт')),
                ('user_template', models.TextField(blank=True, help_text='Доступные переменные: {{grade}} {{subject}} {{topic}} {{duration}}. Разделы и параметры подставляются автоматически.', verbose_name='шаблон USER-сообщения')),
                ('structure', models.JSONField(blank=True, default=list, help_text='Список разделов документа, которые должны быть в материале.', verbose_name='структура документа')),
                ('required_fields', models.JSONField(blank=True, default=list, help_text='Список параметров формы (слаг/имя поля), которые обязательны.', verbose_name='обязательные поля')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Все переменные, например ["grade", "subject", "topic", "duration"].', verbose_name='доступные переменные шаблона')),
            ],
            options={
                'verbose_name': 'тип материала',
                'verbose_name_plural': 'типы материалов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
